// Code generated by re2c 2.2 on Sun Dec 12 11:37:36 2021, DO NOT EDIT.
//go:generate re2go $GOFILE.re -o $GOFILE --no-debug-info -W
package input

func lex(str *[]byte) [][]string { // Go code
	var YYMAXFILL int = 3

	str = pad(str, YYMAXFILL)
	limit := len(*str)
	var cursor, marker int
	var s, s1 int
	var yyt1, yyt2 int
	edge := make([]string, 2)
	edges := make([][]string, 0)

loop:

	{
		var yych byte
		if limit-cursor < 3 {
			panic("yfill")
		}
		yych = (*str)[cursor]
		switch yych {
		case 0x00:
			goto yy2
		case '\n':
			goto yy6
		case 'A':
			fallthrough
		case 'B':
			fallthrough
		case 'C':
			fallthrough
		case 'D':
			fallthrough
		case 'E':
			fallthrough
		case 'F':
			fallthrough
		case 'G':
			fallthrough
		case 'H':
			fallthrough
		case 'I':
			fallthrough
		case 'J':
			fallthrough
		case 'K':
			fallthrough
		case 'L':
			fallthrough
		case 'M':
			fallthrough
		case 'N':
			fallthrough
		case 'O':
			fallthrough
		case 'P':
			fallthrough
		case 'Q':
			fallthrough
		case 'R':
			fallthrough
		case 'S':
			fallthrough
		case 'T':
			fallthrough
		case 'U':
			fallthrough
		case 'V':
			fallthrough
		case 'W':
			fallthrough
		case 'X':
			fallthrough
		case 'Y':
			fallthrough
		case 'Z':
			fallthrough
		case 'a':
			fallthrough
		case 'b':
			fallthrough
		case 'c':
			fallthrough
		case 'd':
			fallthrough
		case 'e':
			fallthrough
		case 'f':
			fallthrough
		case 'g':
			fallthrough
		case 'h':
			fallthrough
		case 'i':
			fallthrough
		case 'j':
			fallthrough
		case 'k':
			fallthrough
		case 'l':
			fallthrough
		case 'm':
			fallthrough
		case 'n':
			fallthrough
		case 'o':
			fallthrough
		case 'p':
			fallthrough
		case 'q':
			fallthrough
		case 'r':
			fallthrough
		case 's':
			fallthrough
		case 't':
			fallthrough
		case 'u':
			fallthrough
		case 'v':
			fallthrough
		case 'w':
			fallthrough
		case 'x':
			fallthrough
		case 'y':
			fallthrough
		case 'z':
			yyt1 = cursor
			goto yy8
		default:
			goto yy4
		}
	yy2:
		cursor += 1
		{
			if limit-cursor == YYMAXFILL-1 {
				return edges
			} else {
				panic("parse error!")
			}
		}
	yy4:
		cursor += 1
	yy5:
		{
			printError(str, cursor-1, cursor)
		}
	yy6:
		cursor += 1
		{
			edges = append(edges, edge)
			edge = make([]string, 2)
			goto loop
		}
	yy8:
		cursor += 1
		marker = cursor
		yych = (*str)[cursor]
		switch yych {
		case '-':
			goto yy9
		case 'A':
			fallthrough
		case 'B':
			fallthrough
		case 'C':
			fallthrough
		case 'D':
			fallthrough
		case 'E':
			fallthrough
		case 'F':
			fallthrough
		case 'G':
			fallthrough
		case 'H':
			fallthrough
		case 'I':
			fallthrough
		case 'J':
			fallthrough
		case 'K':
			fallthrough
		case 'L':
			fallthrough
		case 'M':
			fallthrough
		case 'N':
			fallthrough
		case 'O':
			fallthrough
		case 'P':
			fallthrough
		case 'Q':
			fallthrough
		case 'R':
			fallthrough
		case 'S':
			fallthrough
		case 'T':
			fallthrough
		case 'U':
			fallthrough
		case 'V':
			fallthrough
		case 'W':
			fallthrough
		case 'X':
			fallthrough
		case 'Y':
			fallthrough
		case 'Z':
			fallthrough
		case 'a':
			fallthrough
		case 'b':
			fallthrough
		case 'c':
			fallthrough
		case 'd':
			fallthrough
		case 'e':
			fallthrough
		case 'f':
			fallthrough
		case 'g':
			fallthrough
		case 'h':
			fallthrough
		case 'i':
			fallthrough
		case 'j':
			fallthrough
		case 'k':
			fallthrough
		case 'l':
			fallthrough
		case 'm':
			fallthrough
		case 'n':
			fallthrough
		case 'o':
			fallthrough
		case 'p':
			fallthrough
		case 'q':
			fallthrough
		case 'r':
			fallthrough
		case 's':
			fallthrough
		case 't':
			fallthrough
		case 'u':
			fallthrough
		case 'v':
			fallthrough
		case 'w':
			fallthrough
		case 'x':
			fallthrough
		case 'y':
			fallthrough
		case 'z':
			goto yy11
		default:
			goto yy5
		}
	yy9:
		cursor += 1
		yych = (*str)[cursor]
		switch yych {
		case 'A':
			fallthrough
		case 'B':
			fallthrough
		case 'C':
			fallthrough
		case 'D':
			fallthrough
		case 'E':
			fallthrough
		case 'F':
			fallthrough
		case 'G':
			fallthrough
		case 'H':
			fallthrough
		case 'I':
			fallthrough
		case 'J':
			fallthrough
		case 'K':
			fallthrough
		case 'L':
			fallthrough
		case 'M':
			fallthrough
		case 'N':
			fallthrough
		case 'O':
			fallthrough
		case 'P':
			fallthrough
		case 'Q':
			fallthrough
		case 'R':
			fallthrough
		case 'S':
			fallthrough
		case 'T':
			fallthrough
		case 'U':
			fallthrough
		case 'V':
			fallthrough
		case 'W':
			fallthrough
		case 'X':
			fallthrough
		case 'Y':
			fallthrough
		case 'Z':
			fallthrough
		case 'a':
			fallthrough
		case 'b':
			fallthrough
		case 'c':
			fallthrough
		case 'd':
			fallthrough
		case 'e':
			fallthrough
		case 'f':
			fallthrough
		case 'g':
			fallthrough
		case 'h':
			fallthrough
		case 'i':
			fallthrough
		case 'j':
			fallthrough
		case 'k':
			fallthrough
		case 'l':
			fallthrough
		case 'm':
			fallthrough
		case 'n':
			fallthrough
		case 'o':
			fallthrough
		case 'p':
			fallthrough
		case 'q':
			fallthrough
		case 'r':
			fallthrough
		case 's':
			fallthrough
		case 't':
			fallthrough
		case 'u':
			fallthrough
		case 'v':
			fallthrough
		case 'w':
			fallthrough
		case 'x':
			fallthrough
		case 'y':
			fallthrough
		case 'z':
			yyt2 = cursor
			goto yy13
		default:
			goto yy10
		}
	yy10:
		cursor = marker
		goto yy5
	yy11:
		cursor += 1
		if limit-cursor < 2 {
			panic("yfill")
		}
		yych = (*str)[cursor]
		switch yych {
		case '-':
			goto yy9
		case 'A':
			fallthrough
		case 'B':
			fallthrough
		case 'C':
			fallthrough
		case 'D':
			fallthrough
		case 'E':
			fallthrough
		case 'F':
			fallthrough
		case 'G':
			fallthrough
		case 'H':
			fallthrough
		case 'I':
			fallthrough
		case 'J':
			fallthrough
		case 'K':
			fallthrough
		case 'L':
			fallthrough
		case 'M':
			fallthrough
		case 'N':
			fallthrough
		case 'O':
			fallthrough
		case 'P':
			fallthrough
		case 'Q':
			fallthrough
		case 'R':
			fallthrough
		case 'S':
			fallthrough
		case 'T':
			fallthrough
		case 'U':
			fallthrough
		case 'V':
			fallthrough
		case 'W':
			fallthrough
		case 'X':
			fallthrough
		case 'Y':
			fallthrough
		case 'Z':
			fallthrough
		case 'a':
			fallthrough
		case 'b':
			fallthrough
		case 'c':
			fallthrough
		case 'd':
			fallthrough
		case 'e':
			fallthrough
		case 'f':
			fallthrough
		case 'g':
			fallthrough
		case 'h':
			fallthrough
		case 'i':
			fallthrough
		case 'j':
			fallthrough
		case 'k':
			fallthrough
		case 'l':
			fallthrough
		case 'm':
			fallthrough
		case 'n':
			fallthrough
		case 'o':
			fallthrough
		case 'p':
			fallthrough
		case 'q':
			fallthrough
		case 'r':
			fallthrough
		case 's':
			fallthrough
		case 't':
			fallthrough
		case 'u':
			fallthrough
		case 'v':
			fallthrough
		case 'w':
			fallthrough
		case 'x':
			fallthrough
		case 'y':
			fallthrough
		case 'z':
			goto yy11
		default:
			goto yy10
		}
	yy13:
		cursor += 1
		if limit-cursor < 1 {
			panic("yfill")
		}
		yych = (*str)[cursor]
		switch yych {
		case 'A':
			fallthrough
		case 'B':
			fallthrough
		case 'C':
			fallthrough
		case 'D':
			fallthrough
		case 'E':
			fallthrough
		case 'F':
			fallthrough
		case 'G':
			fallthrough
		case 'H':
			fallthrough
		case 'I':
			fallthrough
		case 'J':
			fallthrough
		case 'K':
			fallthrough
		case 'L':
			fallthrough
		case 'M':
			fallthrough
		case 'N':
			fallthrough
		case 'O':
			fallthrough
		case 'P':
			fallthrough
		case 'Q':
			fallthrough
		case 'R':
			fallthrough
		case 'S':
			fallthrough
		case 'T':
			fallthrough
		case 'U':
			fallthrough
		case 'V':
			fallthrough
		case 'W':
			fallthrough
		case 'X':
			fallthrough
		case 'Y':
			fallthrough
		case 'Z':
			fallthrough
		case 'a':
			fallthrough
		case 'b':
			fallthrough
		case 'c':
			fallthrough
		case 'd':
			fallthrough
		case 'e':
			fallthrough
		case 'f':
			fallthrough
		case 'g':
			fallthrough
		case 'h':
			fallthrough
		case 'i':
			fallthrough
		case 'j':
			fallthrough
		case 'k':
			fallthrough
		case 'l':
			fallthrough
		case 'm':
			fallthrough
		case 'n':
			fallthrough
		case 'o':
			fallthrough
		case 'p':
			fallthrough
		case 'q':
			fallthrough
		case 'r':
			fallthrough
		case 's':
			fallthrough
		case 't':
			fallthrough
		case 'u':
			fallthrough
		case 'v':
			fallthrough
		case 'w':
			fallthrough
		case 'x':
			fallthrough
		case 'y':
			fallthrough
		case 'z':
			goto yy13
		default:
			goto yy15
		}
	yy15:
		s = yyt1
		s1 = yyt2
		{
			edge[0] = asString(str, s, s1-1)
			edge[1] = asString(str, s1, cursor)
			goto loop
		}
	}

	return edges
}
